name: Update Localisation

on:
  #runs at 11:10 UTC every day
  #11:10 UTC = 19:10 CST (China Standard Time)
  #schedule:
  #  - cron: '10 11 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch branch
        run: git checkout -b update-loc

      - name: Get the output zip
        run: |
          curl -X 'GET' \
            'https://paratranz.cn/api/projects/6683/artifacts/download' \
            -H 'accept: */*' \
            -H 'Authorization: ${{ secrets.PARATRANZ_API_TOKEN }}' -L --output text.zip

      - name: Cleanup the folder
        run: |
          rm -r typus-cn-loc
          mkdir typus-cn-loc

      - name: Unzip
        run: |
          mkdir temp
          unzip text.zip -d temp
          cp temp/special/* typus-cn-loc/ -r
          cp temp/chars.txt .

      - name: Cleanup the folder
        run: |
          rm -r temp

      - name: Setup git user
        uses: fregante/setup-git-user@v2

      - name: Commit Changes & Push to Remote Branch
        run: |
          git add -A
          git commit -m "upd: update Chinese Localisation

          Co-authored-by: Cccc_ <47687154+Cccc-owo@users.noreply.github.com>"
          git push -u origin update-loc -f
